### PR TITLE
Fix compilation on OpenBSD

### PR DESCRIPTION
**Pull request by fossifousacid**

### CODE REVIEW

**Comment by Kenix3** [comment]
Is this meant to still be in draft?

**Comment by fossifousacid** [comment]
@Kenix3 I should probably add a build-validation task and ensure that LUS builds with LLVM, as it is the default compiler suite on OpenBSD. I can come back to this after hockey tonight.

**Comment by Kenix3** [comment]
Any news? Thankyou!

**Comment by fossifousacid** [comment]
Hi, I don't have time to work on this this right now as I am currently working overtime. Closing.

**Pull request closed without merging**
