### PR TITLE
Add a missing include in GuiWindows.h

### PR DESCRIPTION
**Pull request by coco875**
Strangely my os complain about unknow defenition of uint32_t so just the import for it

### CODE REVIEW

**Comment by briaguya0** [comment]
could you be more specific about the issue you're facing? what os? also repro steps using a public port repo would be helpful - do you see the same error when building latest dev of https://github.com/HarbourMasters/Shipwright ?

**Comment by coco875** [comment]
when cmake try compile libultraship part he make error about undefined reference of uint32_t, I use fedora 39 with gcc 13.2.1. I will try reproduce it with the repo mentioned

**Comment by coco875** [comment]
I try on Shipwright and don't get the error but the libultraship version on this repo are before https://github.com/Kenix3/libultraship/commit/181465d2abac3bd2914bb58a2f4d2d4016d25708 who introduce uint32_t

**Comment by coco875** [comment]
by updating libultraship to the lastest commit on Shipwright I get the same error 
image

**Pull request merged**
