### PR TITLE
remove some warning

### PR DESCRIPTION
**Pull request by coco875**
warning that I remove:
* remove deplicate macro definition in controller.h. 
* avoid redefine _LANGUAGE_C.
* only add -Wno-implicit-function-declaration when he compile for C or OBJC.
* fix multiple useless typedef.
* add attribute for some unused.
* add cast for when it's not the same type of int (not fixing all).

### CODE REVIEW

**Comment by coco875** [comment]
hmm how you want to add attribute macro ? for other os

**Comment by Kenix3** [comment]
> hmm how you want to add attribute macro ? for other os

We don't really have a standard for this. Will need to do some research to see how it's handled in other projects.

**Comment by louist103** [comment]
> hmm how you want to add attribute macro ? for other os

` [[maybe_unused]] ` and ` [[fallthrough]] ` are in C++ as of c++17 and should work on all platforms

**Comment by Kenix3** [comment]
> > hmm how you want to add attribute macro ? for other os
> 
> `[[maybe_unused]]` and `[[fallthrough]]` are in C++ as of c++17 and should work on all platforms

@coco875

**Review by Kenix3 — APPROVED** [review]

**Pull request merged**
