### PR TITLE
Basic Android Support

### PR DESCRIPTION
**Pull request by Waterdish**
Editing this to mention that I noticed there's already a pull request to implement OpenGL ES. Many of the changes I made are identical, but using the ENABLE_GLES define from that PR is probably better than the Android define I used. Either way, I've confirmed this code works for building and running on Android.

### CODE REVIEW

**Comment by Kenix3** [comment]
Would you mind pointing this at the `next` branch? Thankyou.

**Comment by Waterdish** [comment]
Yeah. Hope most of the code is still compatible with that branch. Let me know if there are any issues. Thanks.

**Comment by Kenix3** [comment]
I'm thinking we might want the opengles define as you mention, since it's not just android that uses opengles. Otherwise the only issue is that you have merge conflicts.

**Comment by Waterdish** [comment]
Will do.

**Comment by Kenix3** [comment]
Any reason this was closed instead of being updated?

**Comment by Waterdish** [comment]
I was updating my port to SOH 8.0.0 and just wanted to close the pull request until I was done tweaking stuff. I think it's all good now. I just need to swap out the GLES define and then I'll reopen it.

**Comment by Kenix3** [comment]
No worries, thankyou for the context. :)

**Pull request closed without merging**
