### PR TITLE
Fixed soh on atmosphere 16.0.0

### PR DESCRIPTION
**Pull request by KiritoDv**

### CODE REVIEW

**Comment by liamwhite** [comment]
Fixes #133

**Comment by leggettc18** [comment]
From my testing, it seems like this will cause SoH not to work for anyone with a pre 16.0.0 switch. Is there a way we can read the firmware version at runtime to fall-back to the current service type?

**Comment by liamwhite** [comment]
@leggettc18 You're not supposed to be using pl:s in the first place, and it should be fine for SoH to have a session to pl:u since it runs as application anyway. Do you have other software installed that might be taking a session, like Tesla menu?

**Comment by leggettc18** [comment]
Oh looks like SoH's current nightly switch build has the same issue so I guess this change isn't the cause. I'm not sure what would be having a session on my switch though. sys-ftpd maybe?

**Comment by leggettc18** [comment]
Well due to a series of unfortunate events I'm no longer confident that I didn't have some other problem on my end and can now no longer test with pre-16.0.0 firmware :(

**Comment by liamwhite** [comment]
I tested this patch with my 15.0.1 Switch, and it worked fine.

**Review by Kenix3 — APPROVED** [review]

**Pull request merged**
